export const headerLinks = [
    {name: "All", link: "/collections/all"},
    {name: "Watches", link: "/collections/watches"},
    {name: "Jewellery Sets", link: "/collections/jewellery-sets"},
    {name: "Dream Stacking", link: "/collections/dream-stacking"},
    {name: "Best Selling", link: "/collections/best-selling"},
    {name: "Bracelets", link: "/collections/bracelets"},
    {name: "Earrings", link: "/collections/earrings"},
    {name: "Rings", link: "/collections/rings"},
    {name: "Pendants", link: "/collections/pendants"},
]

export const products = [
  {
    name: "Classic Silver Watch",
    slug: "classic-silver-watch",
    category: "watches",
    price: 12000,
    salePrice: 10000,
    onSale: true,
    hotSeller: true,
    stock: 15,
    sku: "WCH-001",
    rating: 4.7,
    reviews: 24,
    tags: ["silver", "leather strap", "water-resistant"],
    description: "Elegant silver watch with leather strap, perfect for daily wear and formal occasions.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch1.jpg", "/watch2.jpg", "/watch3.jpg"],
    variants: [
      { color: "silver", strap: "leather", price: 12000, salePrice: 10000, sku: "WCH-001-S" },
      { color: "gold", strap: "leather", price: 12500, salePrice: 10500, sku: "WCH-001-G" }
    ],
    sizes: [],
    createdAt: new Date("2026-01-15")
  },
  {
    name: "Rose Gold Ring",
    slug: "rose-gold-ring",
    category: "rings",
    price: 8000,
    salePrice: 7500,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "RNG-001",
    rating: 4.5,
    reviews: 15,
    tags: ["rose gold", "diamond accent", "adjustable"],
    description: "Exquisite rose gold ring with diamond accents. Comfortable fit and modern design.",
    material: "18K rose gold, diamond",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew1.jpg", "/jew2.jpg", "/jew3.jpg"],
    variants: [
      { material: "rose gold", price: 8000, salePrice: 7500, sku: "RNG-001-RG" },
      { material: "white gold", price: 8500, salePrice: 8000, sku: "RNG-001-WG" }
    ],
    sizes: [5,6,7,8,9],
    createdAt: new Date("2026-01-20")
  },
  {
    name: "Diamond Necklace Set",
    slug: "diamond-necklace-set",
    category: "jewellery sets",
    price: 25000,
    salePrice: 22000,
    onSale: true,
    hotSeller: true,
    stock: 5,
    sku: "JWL-001",
    rating: 4.9,
    reviews: 32,
    tags: ["diamond", "necklace", "earrings", "premium"],
    description: "Premium diamond necklace with matching earrings. Perfect for weddings and parties.",
    material: "18K gold, diamonds",
    care: "Store in soft cloth, avoid perfumes",
    delivery: "5-7 business days",
    images: ["/jew4.jpg", "/jew5.jpg", "/jew6.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-10")
  },
  {
    name: "Stackable Gemstone Bracelets",
    slug: "stackable-gemstone-bracelets",
    category: "dream stacking",
    price: 6000,
    salePrice: 5000,
    onSale: true,
    hotSeller: true,
    stock: 20,
    sku: "BRL-001",
    rating: 4.6,
    reviews: 18,
    tags: ["gemstone", "stackable", "colorful"],
    description: "Colorful gemstone bracelets designed to be stacked. Mix and match your favorite colors.",
    material: "Various gemstones, gold plated",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew6.jpg", "/jew1.jpg"],
    variants: [
      { color: "red", price: 6000, salePrice: 5000, sku: "BRL-001-R" },
      { color: "blue", price: 6000, salePrice: 5000, sku: "BRL-001-B" }
    ],
    sizes: [],
    createdAt: new Date("2026-02-01")
  },
  {
    name: "Stackable Gemstone Braceletss",
    slug: "stackable-gemstone-braceletss",
    category: "dream stacking",
    price: 6000,
    salePrice: 5000,
    onSale: true,
    hotSeller: true,
    stock: 20,
    sku: "BRL-0010",
    rating: 4.6,
    reviews: 18,
    tags: ["gemstone", "stackable", "colorful"],
    description: "Colorful gemstone bracelets designed to be stacked. Mix and match your favorite colors.",
    material: "Various gemstones, gold plated",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew6.jpg", "/jew1.jpg"],
    variants: [
      { color: "red", price: 6000, salePrice: 5000, sku: "BRL-001-R" },
      { color: "blue", price: 6000, salePrice: 5000, sku: "BRL-001-B" }
    ],
    sizes: [],
    createdAt: new Date("2026-02-01")
  },
  {
    name: "Leather Bracelet with Charm",
    slug: "leather-bracelet-with-charm",
    category: "bracelets",
    price: 4000,
    salePrice: 0,
    onSale: false,
    hotSeller: false,
    stock: 25,
    sku: "BRL-002",
    rating: 4.2,
    reviews: 10,
    tags: ["leather", "adjustable", "charm"],
    description: "Stylish leather bracelet featuring a small silver charm. Adjustable for all wrist sizes.",
    material: "Leather, silver charm",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch2.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-02-01")
  },
  {
    name: "Elegant Pearl Earrings",
    slug: "elegant-pearl-earrings",
    category: "earrings",
    price: 7000,
    salePrice: 6500,
    onSale: true,
    hotSeller: true,
    stock: 30,
    sku: "EAR-001",
    rating: 4.8,
    reviews: 22,
    tags: ["pearl", "silver", "classic"],
    description: "Classic pearl earrings with sterling silver hooks. Timeless elegance for every occasion.",
    material: "Pearl, sterling silver",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew3.jpg", "/jew2.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-19")
  },
  {
    name: "Gold Cocktail Ring",
    slug: "gold-cocktail-ring",
    category: "rings",
    price: 15000,
    salePrice: 14000,
    onSale: true,
    hotSeller: true,
    stock: 8,
    sku: "RNG-002",
    rating: 4.7,
    reviews: 16,
    tags: ["gold", "gemstone", "party"],
    description: "Statement gold ring with a large gemstone. Perfect for parties and special events.",
    material: "18K gold, gemstone",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew2.jpg", "/jew3.jpg"],
    variants: [
      { material: "yellow gold", price: 15000, salePrice: 14000, sku: "RNG-002-YG" },
      { material: "white gold", price: 15500, salePrice: 14500, sku: "RNG-002-WG" }
    ],
    sizes: [6,7,8,9,10],
    createdAt: new Date("2026-01-21")
  },
  {
    name: "Minimalist Pendant Necklace",
    slug: "minimalist-pendant-necklace",
    category: "pendants",
    price: 5000,
    salePrice: 4500,
    onSale: true,
    hotSeller: false,
    stock: 12,
    sku: "PND-001",
    rating: 4.5,
    reviews: 8,
    tags: ["gold", "minimalist", "fine chain"],
    description: "Delicate gold pendant on a fine chain. Ideal for layering or wearing alone.",
    material: "18K gold",
    care: "Avoid water and chemicals",
    delivery: "3-5 business days",
    images: ["/jew6.jpg", "/jew5.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-22")
  },
  {
    name: "Silver Hoop Earrings",
    slug: "silver-hoop-earrings",
    category: "earrings",
    price: 3500,
    salePrice: 0,
    onSale: false,
    hotSeller: true,
    stock: 40,
    sku: "EAR-002",
    rating: 4.3,
    reviews: 12,
    tags: ["silver", "hoop", "classic"],
    description: "Classic silver hoop earrings in medium size. Lightweight and comfortable for all-day wear.",
    material: "Sterling silver",
    care: "Clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew5.jpg", "/jew6.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-02-01")
  },
  {
    name: "Vintage Leather Strap Watch",
    slug: "vintage-leather-strap-watch",
    category: "watches",
    price: 13000,
    salePrice: 11000,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "WCH-002",
    rating: 4.6,
    reviews: 14,
    tags: ["vintage", "leather", "classic"],
    description: "Retro-inspired watch with genuine leather strap and minimalist dial design.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch2.jpg", "/watch3.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-27")
  },
  {
    name: "Vintage Leather Strap Watchs",
    slug: "vintage-leather-strap-watchs",
    category: "watches",
    price: 13000,
    salePrice: 11000,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "WCH-0020",
    rating: 4.6,
    reviews: 14,
    tags: ["vintage", "leather", "classic"],
    description: "Retro-inspired watch with genuine leather strap and minimalist dial design.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch3.jpg", "/watch3.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-27")
  },
  {
    name: "Vintage Leather Strap Watchs",
    slug: "vintage-leather-strap-watchs",
    category: "watches",
    price: 13000,
    salePrice: 11000,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "WCH-0020",
    rating: 4.6,
    reviews: 14,
    tags: ["vintage", "leather", "classic"],
    description: "Retro-inspired watch with genuine leather strap and minimalist dial design.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch3.jpg", "/watch3.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-27")
  },
  {
    name: "Vintage Leather Strap Watchs",
    slug: "vintage-leather-strap-watchs",
    category: "watches",
    price: 13000,
    salePrice: 11000,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "WCH-0020",
    rating: 4.6,
    reviews: 14,
    tags: ["vintage", "leather", "classic"],
    description: "Retro-inspired watch with genuine leather strap and minimalist dial design.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch3.jpg", "/watch3.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-27")
  },
  {
    name: "Vintage Leather Strap Watchs",
    slug: "vintage-leather-strap-watchs",
    category: "watches",
    price: 13000,
    salePrice: 11000,
    onSale: true,
    hotSeller: false,
    stock: 10,
    sku: "WCH-0020",
    rating: 4.6,
    reviews: 14,
    tags: ["vintage", "leather", "classic"],
    description: "Retro-inspired watch with genuine leather strap and minimalist dial design.",
    material: "Stainless steel, leather strap",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/watch3.jpg", "/watch3.jpg", "/watch1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-27")
  },
  {
    name: "Sapphire Stud Earrings",
    slug: "sapphire-stud-earrings",
    category: "dream stacking",
    price: 9000,
    salePrice: 8500,
    onSale: true,
    hotSeller: true,
    stock: 18,
    sku: "EAR-003",
    rating: 4.9,
    reviews: 20,
    tags: ["sapphire", "stud", "white gold"],
    description: "Elegant sapphire studs set in white gold. Perfect for gifting or special occasions.",
    material: "Sapphire, 18K white gold",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew2.jpg", "/jew6.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-29")
  },
  {
    name: "Diamond Solitaire Ring",
    slug: "diamond-solitaire-ring",
    category: "dream stacking",
    price: 20000,
    salePrice: 18000,
    onSale: true,
    hotSeller: true,
    stock: 6,
    sku: "RNG-003",
    rating: 5.0,
    reviews: 25,
    tags: ["diamond", "solitaire", "18K gold"],
    description: "Classic solitaire diamond ring in 18K gold. Timeless design for engagements or anniversaries.",
    material: "18K gold, diamond",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew1.jpg", "/jew5.jpg", "/jew1.jpg"],
    variants: [],
    sizes: [5,6,7,8,9],
    createdAt: new Date("2026-01-30")
  },
  {
    name: "Multi-layered Charm Bracelet",
    slug: "multi-layered-charm-bracelet",
    category: "dream stacking",
    price: 7500,
    salePrice: 7000,
    onSale: true,
    hotSeller: false,
    stock: 22,
    sku: "BRL-003",
    rating: 4.4,
    reviews: 10,
    tags: ["multi-layered", "charm", "stackable"],
    description: "Layered bracelet with multiple charms. Perfect for stacking and everyday wear.",
    material: "Gold plated, charms",
    care: "Avoid water, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew3.jpg", "/jew1.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-17")
  },
  {
    name: "Pearl and Diamond Pendant",
    slug: "pearl-and-diamond-pendant",
    category: "pendants",
    price: 12000,
    salePrice: 11000,
    onSale: true,
    hotSeller: true,
    stock: 14,
    sku: "PND-002",
    rating: 4.8,
    reviews: 12,
    tags: ["pearl", "diamond", "gold"],
    description: "Exquisite pearl pendant accented with small diamonds. Elegant and sophisticated.",
    material: "Pearl, 18K gold, diamonds",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew2.jpg", "/jew6.jpg"],
    variants: [],
    sizes: [],
    createdAt: new Date("2026-01-16")
  },
  {
    name: "Gold Eternity Ring",
    slug: "gold-eternity-ring",
    category: "rings",
    price: 18000,
    salePrice: 17000,
    onSale: true,
    hotSeller: true,
    stock: 7,
    sku: "RNG-004",
    rating: 4.9,
    reviews: 18,
    tags: ["gold", "diamonds", "eternity"],
    description: "Beautiful gold eternity ring with diamonds all around. Perfect as a wedding or anniversary band.",
    material: "18K gold, diamonds",
    care: "Avoid chemicals, clean with soft cloth",
    delivery: "3-5 business days",
    images: ["/jew6.jpg", "/jew1.jpg"],
    variants: [],
    sizes: [5,6,7,8,9],
    createdAt: new Date("2026-01-15")
  }
]


export const collections = [
    {image: "/jew1.jpg",name: "All", link: "/collections/all"},
    {image: "/jew2.jpg",name: "Watches", link: "/collections/watches"},
    {image: "/jew3.jpg",name: "Jewellery Sets", link: "/collections/jewellery-sets"},
    {image: "/jew4.jpg",name: "Dream Stacking", link: "/collections/dream-stacking"},
    {image: "/jew5.jpg",name: "Best Selling", link: "/collections/best-selling"},
    {image: "/jew6.jpg",name: "Bracelets", link: "/collections/bracelets"},
    {image: "/watch1.jpg",name: "Earrings", link: "/collections/earrings"},
    {image: "/watch2.jpg",name: "Rings", link: "/collections/rings"},
    {image: "/watch3.jpg",name: "Pendants", link: "/collections/pendants"},
]